import { Zap, Crown, Rocket, Check } from "lucide-react"

export const PRICING_PLANS = [
  {
    id: "basic",
    name: "Basic",
    price: "0",
    docsPerMonth: "5 documents per month",
    icon: Zap,
    features: [
      "5 documents per month",
      "Basic summaries",
      "5 MB file size limit",
      "Email support",
    ],
    buttonText: "Current Plan",
    isCurrent: true,
    badge: "Current Plan",
    badgeColor: "bg-[#43d19d] text-white border-emerald-500/50",
    borderColor: "border-emerald-500/50",
  },
  {
    id: "pro",
    name: "Professional",
    price: "19",
    docsPerMonth: "50 documents per month",
    icon: Crown,
    features: [
      "50 documents per month",
      "Advanced AI summaries",
      "25 MB file size limit",
      "AI chatbot access",
      "Text highlighting & annotations",
      "Priority support",
    ],
    buttonText: "Upgrade Now",
    isPopular: true,
    badge: "Most Popular",
    badgeColor: "bg-[#2dc7f3] text-white border-cyan-500/50",
    borderColor: "border-cyan-500/50",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "49",
    docsPerMonth: "Unlimited documents",
    icon: Rocket,
    features: [
      "Unlimited documents",
      "Premium AI summaries",
      "100 MB file size limit",
      "Advanced AI chatbot",
      "Custom summary templates",
      "Batch processing",
      "API access",
      "24/7 dedicated support",
    ],
    buttonText: "Upgrade Now",
    borderColor: "border-slate-800",
  },
]
